#!/bin/bash
# ============================================================
# release/bundle.sh — Create y8-bundle.js for browser use
#
# Strips ESM import/export, concatenates in dependency order,
# re-exports as a single ESM module.
#
# Usage: ./release/bundle.sh
# Output: release/y8-bundle.js
# ============================================================

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/release/y8-bundle.js"

# Modules in dependency order
MODULES=(
    "src/qjson.js"
    "src/prolog-engine.js"
    "src/parser.js"
    "src/loader.js"
    "src/fossilize.js"
    "src/persist.js"
    "src/qsql.js"
)

{
    echo "// y8-bundle.js — Single-file y8 for browser"
    echo "// Auto-generated by release/bundle.sh — do not edit."
    echo "// $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo ""

    for mod in "${MODULES[@]}"; do
        echo "// ── $(basename "$mod") ────────────────────────────────"
        # Strip import/export lines, keep the rest
        sed -E '/^import /d; /^export /d; /^if \(typeof exports/,/^}/d' "$ROOT/$mod"
        echo ""
    done

    # Re-export everything as ESM
    cat <<'EXPORTS'
// ── Exports ──────────────────────────────────────────────
export {
    qjson_parse, qjson_stringify, js64_encode, js64_decode,
    PrologEngine, termToString, listToArray,
    parseTerm, parseClause, parseProgram,
    fossilize, mineralize,
    qsqlAdapter
};

// Also make available as default for import y8 from '...'
export default {
    parse: qjson_parse, stringify: qjson_stringify,
    Engine: PrologEngine, termToString, listToArray,
    parseTerm, parseClause, parseProgram,
    fossilize, mineralize,
    qsqlAdapter, js64_encode, js64_decode
};
EXPORTS
} > "$OUT"

SIZE=$(wc -c < "$OUT" | tr -d ' ')
LINES=$(wc -l < "$OUT" | tr -d ' ')
echo "Wrote $OUT ($SIZE bytes, $LINES lines)"
